#spring.application.name=api_gateway
#server.port=9000
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8080/realms/ProductService
#logging.level.org.springframework.cloud.gateway=DEBUG

spring:
  main:
    web-application-type: reactive
  application:
    name: api_gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/realms/ProductService

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: product-service
          uri: http://localhost:8083/
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>.*), /${segment}

        - id: inventory
          uri: http://localhost:8082/
          predicates:
            - Path=/api/inventory/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

        - id: order
          uri: http://localhost:8081/
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/orders/(?<segment>.*), /${segment}

        - id: ping-route
          uri: http://localhost:9000
          predicates:
            - Path=/ping

server:
  port: 9000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client: TRACE
